services:
  jupyterlab:
    image: wloving77/ds6600_repo:jupyter_image
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./:/ds6600
    networks:
      - dbnetwork
  postgres:
    image: postgres:latest   
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork
volumes:
  postgresdata:
networks:
  dbnetwork: